





<style>
    .idcard{
 	     font-size: 13px;
     }
    .idcard p {
    	 line-height: 1.5em;
     	margin: 0;            
    }
   .idcard table td, .idcard table th{
   	 vertical-align: top;
/*                 font-weight: 500; */
   }
   .idcard table td{
   		text-align: left;
   }
    div   { page-break-inside:avoid; }
</style>



		<html><script type='text/javascript'>window.print();</script>
		<body>
		<div style='width: 980px;border: 0px solid #000;font-family:Tahoma, Verdana, Segoe, sans-serif;'>
		<div style='margin-bottom: 10px;page-break-inside:avoid;'>
		<div style='width: 45%;margin-bottom:5px; float: left;border: 1px solid #000;border-radius: 5px;height:260px;margin-right:20px; margin: 20px 20px 5px 5px;'  class='idcard'>
		<div style='background: #850c1f;color: #fff;'>
		<div style='float: left;margin: 10px;width:20%;'>
		<img src='image.do?path=/opt/tomcat/webapps/WebSLCMImages/WebSLCM/49441749f742328289079edf04a850d6144300914543017666534531472107617150651170364.jpg' style='max-width: 60px;max-height: 120px;' /></div>
		<div style='width: 75%;float: left;text-align:center;  padding-top: 5px;'><p style='font-size: 16px;'>SLV technology pvt ltd</p><p style='font-size: 13px;'>2nd Floor, B-Block
		IT Park</br>00<br/>Ph: <span style='font-family: arial'>#####</span></p></div>
		<div style='clear: both;'></div></div><div style='width: 70%;float: left;padding-left:5px;'><p style='font-size: 16px;text-align: center;color: #ff5722;margin: 3px auto;font-weight: bold;'>Atarv. </p><table border='0' style='font-size: 13px;color:#062d67;'><tr><th  style='text-align: left;width:18%;' ></th></tr><tr><th  style='text-align: left;width:10%;'>Gender</th><td> : </td><td colspan='2'><b>Male</b></td><th  style='text-align: left;width:18%;' ></th></tr><tr><th  style='text-align: left;width:10%;'>DOB</th><td> : </td><td colspan='2'><b>04/02/2009</b></td><tr><th  style='text-align: left;width:10%;'>Qualification</th><td> : </td><td colspan='2'><b>BE</b></td></tr><tr><th  style='text-align: left;' >Address</th><td> : </td><td style='line-height: 1.5em; text-transform: uppercase;font-size: 11px;'  colspan='3'><b>BS NAGAR</b></td></tr><tr><th  style='text-align: left;'>Contact</th><td> : </td><td colspan='5' style='font-weight:bold;font-family: Arial'>8845759512</td></tr><tr><th  style='text-align: left;'>Designation</th><td> : </td><td colspan='5' style='font-weight:bold;font-family: Arial'></td></tr></table></div><div style='float: left;margin: 10px;width: 24%;text-align: center;'><img src='image.do?path='  style='width: 80px;height: 100px;' /><img src='image.do?path=/opt/tomcat/webapps/WebSLCMImages/WebSLCM/signature/95.png' style='max-height: 20px;margin: 10px auto;' /><b>Secretary</b></div></div><div style='width: 45%;margin-bottom:5px; float: left;border: 1px solid #000;border-radius: 5px;height:260px;margin-right:20px; margin: 20px 20px 5px 5px;'  class='idcard'><div style='background: #850c1f;color: #fff;'><div style='float: left;margin: 10px;width:20%;'><img src='image.do?path=/opt/tomcat/webapps/WebSLCMImages/WebSLCM/49441749f742328289079edf04a850d6144300914543017666534531472107617150651170364.jpg' style='max-width: 60px;max-height: 120px;' /></div><div style='width: 75%;float: left;text-align:center;  padding-top: 5px;'><p style='font-size: 16px;'>SLV technology pvt ltd</p><p style='font-size: 13px;'>2nd Floor, B-Block
IT Park</br>00<br/>Ph: <span style='font-family: arial'>#####</span></p></div><div style='clear: both;'></div></div><div style='width: 70%;float: left;padding-left:5px;'><p style='font-size: 16px;text-align: center;color: #ff5722;margin: 3px auto;font-weight: bold;'>Vividha. </p><table border='0' style='font-size: 13px;color:#062d67;'><tr><th  style='text-align: left;width:18%;' ></th></tr><tr><th  style='text-align: left;width:10%;'>Gender</th><td> : </td><td colspan='2'><b>Female</b></td><th  style='text-align: left;width:18%;' ></th></tr><tr><th  style='text-align: left;width:10%;'>DOB</th><td> : </td><td colspan='2'><b>04/01/2009</b></td><tr><th  style='text-align: left;width:10%;'>Qualification</th><td> : </td><td colspan='2'><b>BE</b></td></tr><tr><th  style='text-align: left;' >Address</th><td> : </td><td style='line-height: 1.5em; text-transform: uppercase;font-size: 11px;'  colspan='3'><b>nava nagar</b></td></tr><tr><th  style='text-align: left;'>Contact</th><td> : </td><td colspan='5' style='font-weight:bold;font-family: Arial'>8157565452</td></tr><tr><th  style='text-align: left;'>Designation</th><td> : </td><td colspan='5' style='font-weight:bold;font-family: Arial'></td></tr></table></div><div style='float: left;margin: 10px;width: 24%;text-align: center;'><img src='image.do?path=null'  style='width: 80px;height: 100px;' /><img src='image.do?path=/opt/tomcat/webapps/WebSLCMImages/WebSLCM/signature/95.png' style='max-height: 20px;margin: 10px auto;' /><b>Secretary</b></div></div><div style='width: 45%;margin-bottom:5px; float: left;border: 1px solid #000;border-radius: 5px;height:260px;margin-right:20px; margin: 20px 20px 5px 5px;'  class='idcard'><div style='background: #850c1f;color: #fff;'><div style='float: left;margin: 10px;width:20%;'><img src='image.do?path=/opt/tomcat/webapps/WebSLCMImages/WebSLCM/49441749f742328289079edf04a850d6144300914543017666534531472107617150651170364.jpg' style='max-width: 60px;max-height: 120px;' /></div><div style='width: 75%;float: left;text-align:center;  padding-top: 5px;'><p style='font-size: 16px;'>SLV technology pvt ltd</p><p style='font-size: 13px;'>2nd Floor, B-Block
IT Park</br>00<br/>Ph: <span style='font-family: arial'>#####</span></p></div><div style='clear: both;'></div></div><div style='width: 70%;float: left;padding-left:5px;'><p style='font-size: 16px;text-align: center;color: #ff5722;margin: 3px auto;font-weight: bold;'>veena. </p><table border='0' style='font-size: 13px;color:#062d67;'><tr><th  style='text-align: left;width:18%;' ></th></tr><tr><th  style='text-align: left;width:10%;'>Gender</th><td> : </td><td colspan='2'><b>Female</b></td><th  style='text-align: left;width:18%;' ></th></tr><tr><th  style='text-align: left;width:10%;'>DOB</th><td> : </td><td colspan='2'><b>06/06/2010</b></td><tr><th  style='text-align: left;width:10%;'>Qualification</th><td> : </td><td colspan='2'><b>BE</b></td></tr><tr><th  style='text-align: left;' >Address</th><td> : </td><td style='line-height: 1.5em; text-transform: uppercase;font-size: 11px;'  colspan='3'><b>sb nagar</b></td></tr><tr><th  style='text-align: left;'>Contact</th><td> : </td><td colspan='5' style='font-weight:bold;font-family: Arial'>8845759512</td></tr><tr><th  style='text-align: left;'>Designation</th><td> : </td><td colspan='5' style='font-weight:bold;font-family: Arial'>null</td></tr></table></div><div style='float: left;margin: 10px;width: 24%;text-align: center;'><img src='image.do?path=null'  style='width: 80px;height: 100px;' /><img src='image.do?path=/opt/tomcat/webapps/WebSLCMImages/WebSLCM/signature/95.png' style='max-height: 20px;margin: 10px auto;' /><b>Secretary</b></div></div><div style='width: 45%;margin-bottom:5px; float: left;border: 1px solid #000;border-radius: 5px;height:260px;margin-right:20px; margin: 20px 20px 5px 5px;'  class='idcard'><div style='background: #850c1f;color: #fff;'><div style='float: left;margin: 10px;width:20%;'><img src='image.do?path=/opt/tomcat/webapps/WebSLCMImages/WebSLCM/49441749f742328289079edf04a850d6144300914543017666534531472107617150651170364.jpg' style='max-width: 60px;max-height: 120px;' /></div><div style='width: 75%;float: left;text-align:center;  padding-top: 5px;'><p style='font-size: 16px;'>SLV technology pvt ltd</p><p style='font-size: 13px;'>2nd Floor, B-Block
IT Park</br>00<br/>Ph: <span style='font-family: arial'>#####</span></p></div><div style='clear: both;'></div></div><div style='width: 70%;float: left;padding-left:5px;'><p style='font-size: 16px;text-align: center;color: #ff5722;margin: 3px auto;font-weight: bold;'>Nagraj Korti. </p><table border='0' style='font-size: 13px;color:#062d67;'><tr><th  style='text-align: left;width:18%;' ></th></tr><tr><th  style='text-align: left;width:10%;'>Gender</th><td> : </td><td colspan='2'><b>Male</b></td><th  style='text-align: left;width:18%;' ></th></tr><tr><th  style='text-align: left;width:10%;'>DOB</th><td> : </td><td colspan='2'><b>30/10/1987</b></td><tr><th  style='text-align: left;width:10%;'>Qualification</th><td> : </td><td colspan='2'><b>B.ed</b></td></tr><tr><th  style='text-align: left;' >Address</th><td> : </td><td style='line-height: 1.5em; text-transform: uppercase;font-size: 11px;'  colspan='3'><b>Bilagi</b></td></tr><tr><th  style='text-align: left;'>Contact</th><td> : </td><td colspan='5' style='font-weight:bold;font-family: Arial'>9986415293</td></tr><tr><th  style='text-align: left;'>Designation</th><td> : </td><td colspan='5' style='font-weight:bold;font-family: Arial'>null</td></tr></table></div><div style='float: left;margin: 10px;width: 24%;text-align: center;'><img src='image.do?path=null'  style='width: 80px;height: 100px;' /><img src='image.do?path=/opt/tomcat/webapps/WebSLCMImages/WebSLCM/signature/95.png' style='max-height: 20px;margin: 10px auto;' /><b>Secretary</b></div></div><div style='clear: both;'></div></div><div style='clear: both;'></div>